version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: minicanvas-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Rei234hila.
      MYSQL_DATABASE: minicanvas_db
      MYSQL_USER: sa
      MYSQL_PASSWORD: Rei234hila.
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306" # Only keep this if you need to access DB from your laptop

  backend:
    image: realgi024/minicanvasproject:latest
    container_name: minicanvas-backend
    depends_on:
      - db
    ports:
      - "80:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/minicanvas_db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=Rei234hila.
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - APP_JWT_SECRET=mySuperSecretKeyThatIsAtLeast32CharactersLong
      - APP_JWT_EXPIRATION_MINUTES=120
      - SERVER_PORT=8081
    restart: always

volumes:
  mysql_data: