server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlserver://localhost:11433;databaseName=MiniCanvasDb;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Rei234hila.}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.upload.assignment-dir=uploads/assignments
app.jwt.secret=${APP_JWT_SECRET:CHANGE_ME_TO_A_LONG_RANDOM_STRING_MIN_32_CHARS}
app.jwt.expiration-minutes=120

gemini.api.key=${GEMINI_API_KEY:dummy-test-key}
gemini.api.url=${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent}