CREATE TABLE ai_chat_messages (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  user_id BIGINT NOT NULL,
                                  role VARCHAR(20) NOT NULL,
                                  message TEXT NOT NULL,
                                  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                  CONSTRAINT fk_ai_chat_messages_user
                                      FOREIGN KEY (user_id)
                                          REFERENCES users(id)
);