CREATE TABLE announcements (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                               title VARCHAR(255) NOT NULL,
                               content TEXT NOT NULL,

                               created_by_user_id BIGINT NOT NULL,

                               created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               updated_at TIMESTAMP NULL,

                               CONSTRAINT fk_announcements_created_by_user
                                   FOREIGN KEY (created_by_user_id)
                                       REFERENCES users(id)
);