CREATE TABLE classes (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(100) NOT NULL UNIQUE,
                         created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE class_memberships (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                   class_id BIGINT NOT NULL,
                                   user_id BIGINT NOT NULL,

                                   class_role VARCHAR(50) NOT NULL,

                                   assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                   CONSTRAINT fk_class_memberships_class
                                       FOREIGN KEY (class_id)
                                           REFERENCES classes(id)
                                           ON DELETE CASCADE,

                                   CONSTRAINT fk_class_memberships_user
                                       FOREIGN KEY (user_id)
                                           REFERENCES users(id)
                                           ON DELETE CASCADE,

                                   CONSTRAINT uq_class_membership_user_class
                                       UNIQUE (class_id, user_id),

                                   CONSTRAINT chk_class_membership_role
                                       CHECK (class_role IN ('STUDENT', 'TEACHER'))
);

INSERT INTO classes(name)
VALUES
    ('MA-FSD-MA-FSD3'),
    ('MA-FSD-MA-FSD2'),
    ('MA-FSD-MA-FSD1');