CREATE TABLE assignments (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                             class_id BIGINT NOT NULL,
                             created_by_user_id BIGINT NOT NULL,

                             title VARCHAR(255) NOT NULL,
                             description TEXT NULL,
                             due_at TIMESTAMP NULL,

                             created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             updated_at TIMESTAMP NULL,

                             CONSTRAINT fk_assignments_class
                                 FOREIGN KEY (class_id)
                                     REFERENCES classes(id)
                                     ON DELETE CASCADE,

                             CONSTRAINT fk_assignments_created_by_user
                                 FOREIGN KEY (created_by_user_id)
                                     REFERENCES users(id)
);

CREATE TABLE assignment_submissions (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                        assignment_id BIGINT NOT NULL,
                                        student_user_id BIGINT NOT NULL,

                                        original_file_name VARCHAR(255) NOT NULL,
                                        stored_file_name VARCHAR(255) NOT NULL,
                                        file_path VARCHAR(500) NOT NULL,
                                        content_type VARCHAR(100) NULL,
                                        file_size BIGINT NOT NULL,

                                        comment TEXT NULL,

                                        submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                        updated_at TIMESTAMP NULL,

                                        CONSTRAINT fk_assignment_submissions_assignment
                                            FOREIGN KEY (assignment_id)
                                                REFERENCES assignments(id)
                                                ON DELETE CASCADE,

                                        CONSTRAINT fk_assignment_submissions_student
                                            FOREIGN KEY (student_user_id)
                                                REFERENCES users(id),

                                        CONSTRAINT uq_assignment_student_submission
                                            UNIQUE (assignment_id, student_user_id)
);